[package]
name = "rexif"
version = "0.5.1"
authors = ["Elvis Pfützenreuter <epxx@epxx.co>", "Kornel <kornel@geekhood.net>", "Gabriela Alexandra Moldovan <gabi@cloudflare.com>"]
include = ["src/*.rs", "Cargo.toml", "README.md", "LICENSE"]
description = "RExif is a native Rust crate, written to extract EXIF data from JPEG and TIFF images."
license = "MIT"
categories = ["multimedia::images", "parser-implementations"]
documentation = "https://docs.rs/rexif"
homepage = "https://lib.rs/crates/rexif"
keywords = ["exif", "metadata", "tiff", "tag", "gps"]
readme = "README.md"
repository = "https://github.com/kornelski/rexif.git"
edition = "2018"

[lib]
name = "rexif"
path = "src/lib.rs"

[dependencies]
num = "0.3.0"
log = "0.4.11"
log4rs = "0.13.0"

[dev-dependencies]
glob = "0.3.0"

[[bin]]
name = "rexiftool"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
